# ==========================================
# DRAIN FORTIN APPLICATION ALERTS
# Prometheus Alert Rules
# ==========================================

groups:
  # ==========================================
  # FRONTEND APPLICATION ALERTS
  # ==========================================
  - name: frontend_alerts
    rules:
      - alert: FrontendDown
        expr: up{job="drain-fortin-frontend"} == 0
        for: 2m
        labels:
          severity: critical
          service: frontend
          environment: production
        annotations:
          summary: "Frontend application is down"
          description: "Frontend application has been down for more than 2 minutes"
          runbook_url: "https://docs.drainfortin.com/runbooks/frontend-down"

      - alert: FrontendHighErrorRate
        expr: rate(http_requests_total{status=~"5..", job="drain-fortin-frontend"}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: frontend
          environment: production
        annotations:
          summary: "High error rate in frontend"
          description: "Frontend error rate is {{ $value | humanizePercentage }} for the last 5 minutes"

      - alert: FrontendHighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="drain-fortin-frontend"}[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: frontend
          environment: production
        annotations:
          summary: "High response time in frontend"
          description: "Frontend 95th percentile response time is {{ $value }}s"

      - alert: FrontendLowSuccessRate
        expr: rate(http_requests_total{status="200", job="drain-fortin-frontend"}[5m]) / rate(http_requests_total{job="drain-fortin-frontend"}[5m]) < 0.95
        for: 5m
        labels:
          severity: warning
          service: frontend
          environment: production
        annotations:
          summary: "Low success rate in frontend"
          description: "Frontend success rate is {{ $value | humanizePercentage }}"

  # ==========================================
  # SUPABASE BACKEND ALERTS
  # ==========================================
  - name: supabase_alerts
    rules:
      - alert: SupabaseUnhealthy
        expr: up{job="supabase-health"} == 0
        for: 3m
        labels:
          severity: critical
          service: supabase
          environment: production
        annotations:
          summary: "Supabase backend is unhealthy"
          description: "Supabase backend health check has failed for more than 3 minutes"
          runbook_url: "https://docs.drainfortin.com/runbooks/supabase-down"

      - alert: SupabaseSlowResponse
        expr: http_request_duration_seconds{job="supabase-health"} > 5
        for: 5m
        labels:
          severity: warning
          service: supabase
          environment: production
        annotations:
          summary: "Supabase slow response time"
          description: "Supabase response time is {{ $value }}s"

      - alert: SupabaseWebhookErrors
        expr: increase(supabase_function_errors_total{function="vapi-webhook"}[5m]) > 5
        for: 2m
        labels:
          severity: critical
          service: supabase
          component: webhook
          environment: production
        annotations:
          summary: "High error rate in VAPI webhook"
          description: "{{ $value }} errors in VAPI webhook function in the last 5 minutes"

  # ==========================================
  # VAPI SERVICE ALERTS
  # ==========================================
  - name: vapi_alerts
    rules:
      - alert: VAPIServiceDown
        expr: up{job="vapi-health"} == 0
        for: 5m
        labels:
          severity: critical
          service: vapi
          environment: production
        annotations:
          summary: "VAPI service is down"
          description: "VAPI service has been unreachable for more than 5 minutes"
          runbook_url: "https://docs.drainfortin.com/runbooks/vapi-down"

      - alert: VAPIHighCallFailureRate
        expr: rate(vapi_calls_failed_total[5m]) / rate(vapi_calls_total[5m]) > 0.1
        for: 3m
        labels:
          severity: warning
          service: vapi
          environment: production
        annotations:
          summary: "High call failure rate in VAPI"
          description: "VAPI call failure rate is {{ $value | humanizePercentage }}"

      - alert: VAPILowCallVolume
        expr: rate(vapi_calls_total[10m]) < 0.01
        for: 30m
        labels:
          severity: info
          service: vapi
          environment: production
        annotations:
          summary: "Low call volume in VAPI"
          description: "VAPI receiving unusually low call volume: {{ $value }} calls/minute"

  # ==========================================
  # TWILIO INTEGRATION ALERTS
  # ==========================================
  - name: twilio_alerts
    rules:
      - alert: TwilioSMSFailures
        expr: rate(twilio_sms_failed_total[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
          service: twilio
          component: sms
          environment: production
        annotations:
          summary: "High SMS failure rate"
          description: "Twilio SMS failure rate is {{ $value | humanizePercentage }}"

      - alert: TwilioHighLatency
        expr: histogram_quantile(0.95, rate(twilio_request_duration_seconds_bucket[5m])) > 10
        for: 5m
        labels:
          severity: warning
          service: twilio
          environment: production
        annotations:
          summary: "High Twilio API latency"
          description: "Twilio API 95th percentile latency is {{ $value }}s"

  # ==========================================
  # BUSINESS LOGIC ALERTS
  # ==========================================
  - name: business_alerts
    rules:
      - alert: HighPriorityCallsUnprocessed
        expr: drain_fortin_calls_priority_1_unprocessed > 0
        for: 1m
        labels:
          severity: critical
          service: business
          priority: P1
          environment: production
        annotations:
          summary: "High priority calls unprocessed"
          description: "{{ $value }} P1 calls are unprocessed (flooding situations)"
          runbook_url: "https://docs.drainfortin.com/runbooks/p1-calls"

      - alert: LowConversionRate
        expr: drain_fortin_conversion_rate_1h < 0.15
        for: 15m
        labels:
          severity: warning
          service: business
          environment: production
        annotations:
          summary: "Low conversion rate"
          description: "Conversion rate is {{ $value | humanizePercentage }} in the last hour"

      - alert: RevenueDropAlert
        expr: (drain_fortin_revenue_24h - drain_fortin_revenue_24h offset 24h) / drain_fortin_revenue_24h offset 24h < -0.2
        for: 10m
        labels:
          severity: warning
          service: business
          environment: production
        annotations:
          summary: "Significant revenue drop"
          description: "Revenue dropped {{ $value | humanizePercentage }} compared to yesterday"

  # ==========================================
  # INFRASTRUCTURE ALERTS
  # ==========================================
  - name: infrastructure_alerts
    rules:
      - alert: SSLCertificateExpiringSoon
        expr: ssl_certificate_expiry_days < 30
        for: 1h
        labels:
          severity: warning
          service: infrastructure
          component: ssl
          environment: production
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.instance }} expires in {{ $value }} days"

      - alert: DomainDNSResolutionFailure
        expr: probe_success{job="blackbox-http"} == 0
        for: 5m
        labels:
          severity: critical
          service: infrastructure
          component: dns
          environment: production
        annotations:
          summary: "Domain DNS resolution failure"
          description: "DNS resolution failed for {{ $labels.instance }}"

      - alert: CDNHighErrorRate
        expr: cloudflare_zone_requests_status_2xx / cloudflare_zone_requests_total < 0.95
        for: 5m
        labels:
          severity: warning
          service: infrastructure
          component: cdn
          environment: production
        annotations:
          summary: "CDN high error rate"
          description: "CDN success rate is {{ $value | humanizePercentage }}"