# Supabase Project Configuration
project_id = "phiduqxcufdmgjvdipyu"

[api]
enabled = true
port = 54321
schemas = ["public", "auth", "storage"]
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enable_signup = true
enable_anonymous_sign_ins = false
site_url = "https://drainfortin.com"
additional_redirect_urls = ["https://www.drainfortin.com"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.sms]
enable_signup = true
enable_confirmations = true
template = "Your Drain Fortin code is {{ .Code }}"
max_frequency = "5s"

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324

[functions]
"vapi-webhook" = { verify_jwt = false }
"send-sms" = { verify_jwt = false }

[analytics]
enabled = false